### ISSUE TITLE
Does libyang really need debhelper 11 and Swig 3.0.12?

### ISSUE THREAD

**Issue by njh** [opensourcerouting/libyang-debian#2]
Hi,

I am trying to build a libyang Debian package for use on VyOS. The current version of VyOS uses Debian jessie as a base, which comes with debhelper 9 and Swig 2.0.12.

Is there a reason why libyang depends on newer versions of debhelper and swig, or did you just set it to what comes with more recent versions of Debian?

Thanks,

nick.

**Comment by eqvinox** [comment]
* Swig 3.0.12: yes, it's needed.  The only "workaround" would be to disable the C++ and Python bindings.
* debhelper 11: the current packaging relies on it, so just editing it out won't work.  The major difference is library installation paths (`/usr/lib/<multiarch>` on dh11), you'd need to change that for dh9.

However, the solution for your problem is far easier than this:  build the packages on Debian buster and use them on jessie and stretch.  I have tested and verified this works and will check into keeping it this way.  This applies for the following binary packages:

* libyang0.16
* libyang-cpp0.16
* libyang-dev
* libyang-cpp-dev
* yang-tools

The Python packages will _**not**_ work on jessie/stretch, i.e.:
* python3-yang
* python3-yang-dbg

**Comment by njh** [comment]
Thank you very much, that is really helpful.

I will have a go at building it on buster

**Comment by njh** [comment]
I have successfully built libyang on Buster Virtual Machine using `dpkg-buildpackage -uc -us -tc -b`, which created the following packages:

```
libyang-cpp-dev_0.16.105-1_i386.deb
libyang-cpp0.16-dbgsym_0.16.105-1_i386.deb
libyang-cpp0.16_0.16.105-1_i386.deb
libyang-dev_0.16.105-1_i386.deb
libyang0.16-dbgsym_0.16.105-1_i386.deb
libyang0.16_0.16.105-1_i386.deb
python3-yang-dbg_0.16.105-1_i386.deb
python3-yang_0.16.105-1_i386.deb
yang-tools-dbgsym_0.16.105-1_i386.deb
yang-tools_0.16.105-1_i386.deb
```

I also successfully `dpkg -i` installed `libyang0.16` and `yang-tools` on a Jeesie virtual machines.

However when trying to run the lb / live-build command to build the ISO, I get a weird error:

```
E: Sub-process false received signal 2.
E: Errors apply to file './libyang0.16_0.16.105-1_i386.deb'
```

I am getting the same problem with version 0.16.52.
It isn't a very helpful error message, so I have no idea if there is a problem with libyang or if something else is going on...

**Comment by eqvinox** [comment]
Hm, I've never worked on building debian live ISOs, so I know exactly nothing about the process for that and can't really help you :frowning_face: ... there's _got_ to be some way to get more verbose output though?

**Comment by eqvinox** [comment]
Wait - did you sign the resulting .deb?  I think dpkg -i will accept unsigned .debs, but live-build maybe doesn't?

**Comment by njh** [comment]
Good thought but I am installing other unsigned .deb packages, so I suspect that isn't the problem. I don't have any experience with building live ISOs either.

I have tried running with `--debug` and `--verbose` but that doesn't seem to give anything more helpful.

I suspect that `false` is referring to `/bin/false` but I am not sure what is trigging that to be run.

I will close this issue my original issue is answered.
